import { createContext, useState, useEffect } from "react";
import livro1 from "../assets/livros/livro1.jpeg";
import livro2 from "../assets/livros/livro2.jpeg";
import livro3 from "../assets/livros/livro3.jpeg";
import livro4 from "../assets/livros/livro4.jpeg";
import livro5 from "../assets/livros/livro5.jpeg";
import livro6 from "../assets/livros/livro6.jpeg";
import livro7 from "../assets/livros/livro7.jpeg";
import livro8 from "../assets/livros/livro8.jpeg";
import livro9 from "../assets/livros/livro9.jpeg";
import livro10 from "../assets/livros/livro10.jpeg";
import livro11 from "../assets/livros/livro11.jpeg";
import livro12 from "../assets/livros/livro12.jpeg";
import livro13 from "../assets/livros/livro13.jpeg";
import livro14 from "../assets/livros/livro14.jpeg";
import livro15 from "../assets/livros/livro15.jpeg";
import livro16 from "../assets/livros/livro16.jpeg";
import livro17 from "../assets/livros/livro17.jpeg";
import livro18 from "../assets/livros/livro18.jpeg";
import livro19 from "../assets/livros/livro19.jpeg";
import livro20 from "../assets/livros/livro20.jpeg";
import livro21 from "../assets/livros/livro21.jpeg";
import livro22 from "../assets/livros/livro22.jpeg";
import livro23 from "../assets/livros/livro23.jpeg";
import livro24 from "../assets/livros/livro24.jpeg";
import livro25 from "../assets/livros/livro25.jpeg";
import livro26 from "../assets/livros/livro26.jpeg";
import livro27 from "../assets/livros/livro27.jpeg";
import livro28 from "../assets/livros/livro28.jpeg";
import livro29 from "../assets/livros/livro29.jpeg";
import livro30 from "../assets/livros/livro30.jpeg";

// Criação do contexto
export const LivrosContext = createContext();

export function LivrosProvider({ children }) {
  const [livros, setLivros] = useState([]);

  useEffect(() => {
    // Mock dos livros //Já deveriam estar vindo de algum endpoint público da api no backend.
    const mockLivros = [
    {
      id: 1,
      titulo: "A Guerra dos Tronos: As Crônicas de Gelo e Fogo - Volume 1",
      preco: 79.9,
      imagem: livro1,
      sinopse:
        "A guerra dos tronos é o primeiro livro da série best-seller internacional As Crônicas de Gelo e Fogo, que deu origem à adaptação de sucesso da HBO, Game of Thrones. O verão pode durar décadas. O inverno, toda uma vida. E a guerra dos tronos começou. Como Guardião do Norte, lorde Eddard Stark não fica feliz quando o rei Robert o proclama a nova Mão do Rei. Sua honra o obriga a aceitar o cargo e deixar seu posto em Winterfell para rumar para a corte, onde os homens fazem o que lhes convém, não o que devem... e um inimigo morto é algo a ser admirado. Longe de casa e com a família dividida, Eddard se vê cada vez mais enredado nas intrigas mortais do Porto Real, sem saber que perigos ainda maiores esperam à distância. Nas frias torres de Winterfell, forças sobrenaturais se espalham por trás da Muralha que protege a região. E, nas Cidades Livres, o jovem Rei Dragão exilado na Rebelião de Robert planeja sua vingança e deseja recuperar sua herança de família: o Trono de Ferro de Westeros.",
        genero: "Fantasia",
        colecao: "As Crônicas de Gelo e Fogo",
        quantidade: 5,
        formato: "Físico",
        numeroDePaginas: 592,
        editora: "Leya",
        vendas: 5200,
        lancamento: "1996-08-06",
        avaliacao: 4.3
      },
    {
      id: 2,
      titulo: "A Fúria dos Reis: As Crônicas de Gelo e Fogo - Volume 2",
      autor: "George R. R. Martin",
      preco: 79.9,
      imagem: livro2,
      sinopse: "Um cometa da cor de fogo e sangue corta os céus. E, da antiga cidadela de Pedra do Dragão às costas áridas de Winterfell, reina o caos. Em A fúria dos reis , seis facções disputam o controle de uma terra dividida e o direito de ocupar o Trono de Ferro de Westeros – e estão dispostos a encarar tempestades, levantes e guerras para isso. Nesta história, irmão trama contra irmão e os mortos se levantam para caminhar pela noite. Aqui, uma princesa se disfarça de menino órfão, um cavaleiro se prepara para encarar uma pérfida feiticeira e bárbaros descem das Montanhas da Lua para saquear os campos. Em um contexto de incesto e fratricídio, alquimia e assassinato, a vitória será dos homens e mulheres que possuírem o mais frio aço... e o mais frio coração. Pois, quando se desperta a fúria dos reis, a terra inteira treme.",
      genero: "Fantasia",
      colecao: "As Crônicas de Gelo e Fogo",
      quantidade: 5,
      formato: "Físico",
      numeroDePaginas: 648,
      editora: "Suma",
      vendas: 2280,
      lancamento: "1998-11-16",
      avaliacao: 4.1
    },
    {
      id: 3,
      titulo: "A Tormenta de Espadas: As Crônicas de Gelo e Fogo - Volume 3",
      autor: "George R. R. Martin",
      preco: 87.9,
      imagem: livro3,
      sinopse: "O futuro de Westeros está em jogo, e ninguém descansará até que os Sete Reinos tenham explodido em uma verdadeira tormenta de espadas. Dos cinco pretendentes ao trono, um está morto e outro caiu em desgraça, e ainda assim a guerra continua em toda sua fúria, enquanto alianças são feitas e desfeitas. Joffrey, da Casa Lannister, ocupa o Trono de Ferro, como o instável governante dos Sete Reinos, ao passo que seu rival mais amargo, lorde Stannis, jaz derrotado e enfeitiçado pelas promessas da Mulher Vermelha. O jovem Robb, da Casa Stark, ainda comanda o Norte, contudo, e planeja sua batalha contra os Lannister, mesmo que sua irmã seja refém deles em Porto Real. Enquanto isso, Daenerys Targaryen atravessa um continente deixando um rastro de sangue a caminho de Westeros, levando consigo os três únicos dragões existentes em todo o mundo. Enquanto forças opostas avançam para uma gigantesca batalha final, um exército de selvagens chega dos confins da civilização. Em seu rastro vem uma horda de terríveis criaturas místicas – os Outros: um batalhão de mortos-vivos cujos corpos são imparáveis.",
      genero: "Fantasia",
      colecao: "As Crônicas de Gelo e Fogo",
      quantidade: 5,
      formato: "Físico",
      numeroDePaginas: 832,
      editora: "Suma",
      vendas: 4280,
      lancamento: "2000-08-08",
      avaliacao: 4.9
    },
  {
    id: 4,
    titulo: "O Festim dos Corvos: As Crônicas de Gelo e Fogo - Volume 4",
    autor: "George R. R. Martin",
    preco: 79.9,
    imagem: livro4,
    sinopse: "O festim dos corvos é o quarto livro da monumental saga de fantasia As Crônicas de Gelo e Fogo, sucesso internacional que deu origem a Game of Thrones. Neste livro, Martin coloca um reino dilacerado à beira da paz... só para ser lançado de novo rumo ao terror e à destruição. Há séculos os sete grandes reinos de Westeros se enfrentam em amargas disputas, batalhas e traições. Agora, com Joffrey Baratheon e Robb Stark fora da jogada e lordes insignificantes competindo pelas Ilhas de Ferro, a guerra que devorou o continente parece ter finalmente chegado ao fim No entanto, como após todo grande conflito, não demora para que os sobreviventes, os bandidos, os renegados e os carniceiros avancem para disputar o espólio dos mortos. Por toda Westeros os lordes se agitam, formando alianças e fazendo planos, enquanto nomes conhecidos e desconhecidos se apresentam para tomar parte das danças políticas Todos precisam lançar mão de suas habilidades e poderes para encarar os tempos de terror que se aproximam. Nobres e plebeus, soldados e feiticeiros, assassinos e saqueadores devem arriscar suas fortunas... e suas vidas, pois em um festim de corvos, muitos são os convidados ― e poucos os sobreviventes.",
    genero: "Fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "Físico",
    numeroDePaginas: 608,
    editora: "Suma",
    vendas: 3970,
    lancamento: "2005-10-17",
    avaliacao: 4.0
  },
  {
    id: 5,
    titulo: "A Dança dos Dragões: As Crônicas de Gelo e Fogo - Volume 5",
    autor: "George R. R. Martin",
    preco: 89.9,
    imagem: livro5,
    sinopse: "A dança dos dragões é o quinto livro da saga As Crônicas de Gelo e Fogo, dando continuidade à trama de O festim dos corvos e trazendo personagens novos e conhecidos em disputas acirradas por um reino à beira da ruína. É outono em Westeros, e a Guerra dos Cinco Reis parece finalmente entrar na reta final. Stannis Baratheon se instala no Norte e jura conquistar o apoio dos senhores da região para continuar sua luta pelo trono, embora seja atrapalhado pela invasão de homens de ferro em grande parte da costa. Na Muralha, Jon Snow é eleito o 998º Senhor Comandante da Patrulha da Noite, mas inimigos o cercam de todos os lados, tanto na Patrulha quanto para além da Muralha. Enquanto isso, Tyrion Lannister atravessa o Mar Estreito rumo a Pentos, sem objetivos definidos, sem aliados e cada vez mais sem opções. Na Baía dos Escravos, Daenerys Targaryen conquista a cidade de Meereen e decide ficar e governá-la, praticando as habilidades de liderança que serão tão necessárias quando partir para Westeros. No entanto, sua presença já foi notada por muitos senhores nos Sete Reinos, e das Ilhas de Ferro e de Dorne, de Vilavelha e das Cidades Livres, emissários estão a caminho, querendo se unir à sua causa e, se possível, usá-la para os próprios fins. Em todos os cantos conflitos ganham vida e traições vêm daqueles mais próximos. Guerreiros, selvagens, nobres e escravos – todos têm pela frente um longo inverno, enquanto destino, ambição e política ditam o ritmo da dança mais perigosa de todas.",
    genero: "Fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "Físico",
    numeroDePaginas: 824,
    editora: "Suma",
    vendas: 5070,
    lancamento: "2011-07-12",
    avaliacao: 4.8
  },
  {
    id: 6,
    titulo: "Fogo & Sangue – Volume 1",
    preco: 62.39,
    imagem: livro6,
    sinopse: "A arrebatadora história dos Targaryen ganha vida neste novo livro de George R.R. Martin, autor de As Crônicas de Gelo e Fogo, série que inspirou a adaptação de sucesso da HBO, Game of Thrones. Séculos antes dos eventos de A guerra dos tronos, a Casa Targaryen – única família de senhores dos dragões a sobreviver à Destruição de Valíria – tomou residência em Pedra do Dragão. A história de Fogo e sangue começa com o lendário Aegon, o Conquistador, criador do Trono de Ferro, e segue narrando as gerações de Targaryen que lutaram para manter o assento, até a guerra civil que quase destruiu sua dinastia. O que realmente aconteceu durante a Dança dos Dragões? Por que era tão perigoso visitar Valíria depois da Destruição? Qual é a origem dos três ovos de dragão que chegaram a Daenerys? Essas são algumas das questões respondidas neste livro essencial, relatadas por um sábio meistre da Cidadela. Ricamente ilustrado com mais de oitenta imagens em preto e branco assinadas pelo artista Dough Wheatley, Fogo e sangue dará aos leitores uma nova e completa visão da fascinante história de Westeros – um livro imperdível para os fãs do autor.",
    autor: "George R. R. Martin",
    genero: "fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "fisico",
    numeroDePaginas: 664,
    editora: "Suma",
    vendas: 2974,
    lancamento: "2018-11-20",
    avaliacao: 4.4
    },
    {
    id: 7,
    titulo: "O Cavaleiro dos Sete Reinos",
    preco: 120.00,
    imagem: livro7,
    sinopse: "Duzentos anos após a Conquista, a dinastia Targaryen vive seu auge. Os Sete Reinos de Westeros atravessam um tempo de relativa paz, nos últimos anos do reinado do Bom Rei Daeron.É neste cenário que Dunk, um menino pobre da Baixada das Pulgas, tem uma chance única: deixar a vida miserável em Porto Real para se tornar escudeiro de um cavaleiro andante. Quando adulto, o cavaleiro morre e Dunk decide tomar seu lugar e fazer fama no torneio de Campina de Vaufreixo.É quando conhece Egg, um menino de dez anos, cabeça totalmente raspada, que é muito mais do que aparenta ser. Dunk aceita Egg como seu escudeiro e, juntos, viajam por Westeros em busca de trabalho e aventuras. Uma grande amizade nasce entre eles uma amizade pela vida toda, mesmo quando, anos mais tarde, os dois personagens assumem papéis centrais na estrutura de poder dos Sete Reinos.As aventuras de Dunk e Egg trazem para os fãs de As Crônicas de Gelo e Fogo a oportunidade única de vivenciar outro momento da história de Westeros, de conhecer e analisar fatos que teriam desdobramentos noventa anos depois, na guerra dos tronos.",
    autor: "George R. R. Martin",
    genero: "fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "fisico",
    numeroDePaginas: 400,
    editora: "Leya",
    vendas: 5023,
    lancamento: "2015-10-06",
    avaliacao: 4.3
    },
    {
    id: 8,
    titulo: "A Ascensão do Dragão: Uma História Ilustrada da Dinastia Targaryen – Volume 1",
    preco: 113.56,
    imagem: livro8,
    sinopse: "A Ascensão do Dragão é um guia excepcional sobre a casa mais poderosa de Westeros, com 180 ilustrações inéditas dos Targaryen, de seus dragões e das tradições dos Sete Reinos. Durante os séculos em que os Targaryen ocuparam o Trono de Ferro, seus dragões comandaram os céus. A jornada da única família de senhores de dragões que sobreviveu à Destruição de Valíria é o retrato de uma política tortuosa forjada por atos nobres e covardes, alianças e traições. Como no épico romance Fogo & Sangue , A Ascensão do Dragão retoma o surgimento dos Targaryen e sua chegada ao poder, desde a conquista de Westeros por Aegon Targaryen até a infame Dança dos Dragões ― a sangrenta guerra civil que quase destruiu de uma vez por todas seu reinado.“Um livro que todo fã de A Guerra dos Tronos e A Casa do Dragão deve ter na estante. A Ascensão do Dragão é magnífico.” ― Forbes",
    autor: "George R. R. Martin",
    genero: "fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "fisico",
    numeroDePaginas: 352,
    editora: "Leya",
    vendas: 2974,
    lancamento: "2022-10-25",
    avaliacao: 4.5
    },
    {
    id: 9,
    titulo: "O Mundo de Gelo e Fogo",
    preco: 662.00,
    imagem: livro9,
    sinopse: "Tudo o que você sempre quis saber sobre Westeros e tinha medo de perguntar a George R. R. Martin. A saga dos personagens de Crônicas de Gelo e Fogo não começou com as disputas pelo trono de ferro. Este Guia inédito e ricamente ilustrado reúne um amplo material inédito que se estende desde a Era da Aurora até a Era do Heróis; a partir da vinda do primeiros homens até a chegada de Aegon, o Conquistador; da conquista de Aegon do Trono de Ferro até a Rebelião de Robert e da queda do Rei Louco, Aerys II Targaryen, o que tem causado as atuais lutas dos Starks, Lannisters, Baratheon e Targaryen. Esta edição de luxo traz também informações e detalhes preciosos sobre todas as casas dos Sete Reinos e as cidades além do Reino do Pôr do Sol, e a árvore genealógica dos Targaryen e Starks",
    autor: "George R. R. Martin",
    genero: "fantasia",
    colecao: "As Crônicas de Gelo e Fogo",
    quantidade: 5,
    formato: "fisico",
    numeroDePaginas: 336,
    editora: "Leya",
    vendas: 4974,
    lancamento: "2014-10-28",
    avaliacao: 4.6
    },
    {
    id: 10,
    titulo: "Crime e Castigo",
    preco: 15.50,
    imagem: livro10,
    sinopse: "A pobreza assola Raskólnikov, que precisa pagar os estudos e o aluguel de onde mora. Orgulhoso, acredita que é inteligente o suficiente para planejar um crime perfeito, julgando que seu bom motivo e futuro promissor justificariam o ato. Os limites da moralidade comum também o atingem e ele é sentenciado. A culpa o acompanha na jornada em busca de redenção e boas perspectivas. Dostoiévski traz a psicologia criminal para este romance, abordando moralidade e a margem da dignidade nas ruas das cidades.",
    autor: "Fiódor Dostoiévski",
    genero: "ficcao",
    colecao: "",
    quantidade: 5,
    formato: "fisico",
    numeroDePaginas: 240,
    editora: "Principis",
    vendas: 274,
    lancamento: "2020-18-03",
    avaliacao: 4.5
    },
    {
      id: 11,
      titulo: "A Cirurgiã - Um Thriller Psicológico Eletrizante, Repleto de Reviravoltas.",
      preco: 29.64,
      imagem: livro11,
      sinopse: "Cirurgiã renomada, esposa amorosa e... assassina? Antes de seu mundo desabar, a doutora Anne Wiley tinha uma vida perfeita. A carreira de sucesso que sempre almejou conquistar, uma bela casa onde poderia descansar confortavelmente após um longo dia de trabalho e um marido extremamente dedicado e cuidadoso, cujo sorriso sempre a manteve segura. Até aquele momento, ela nunca tinha perdido um paciente. Mas também nunca havia operado alguém que odiava. No minuto seguinte em que declarou o óbito, toda a equipe médica na sala de operações a observou em silêncio, confusos e preocupados. O olhar de Anne transmitia medo, o coração batia acelerado e as mãos tremiam e suavam dentro das luvas. Seus doze anos de experiência são colocados sob suspeita quando é descoberto quem era o paciente que faleceu em suas mãos. Empenhada em acusar a doutora de assassinato, a promotora criminal Paula Fuselier começa a investigar. No entanto, tanto Anne quanto a promotora têm algo muito particular em comum – um relacionamento com Derreck, marido de Anne, que é candidato a prefeito, e qualquer escândalo pode prejudicar sua carreira na vida pública. Um suspense psicológico totalmente envolvente que fará você correr pelas páginas até o final.",
      autor: "Leeslie Wolfe",
      genero: "ficcao",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 244,
      editora: "Faro Editorial",
      vendas: 1274,
      lancamento: "2024-03-04",
      avaliacao: 4.0
    },
    {
      id: 12,
      titulo: "A Biblioteca da Meia-Noite.",
      preco: 40.87,
      imagem: livro12,
      sinopse: "Aos 35 anos, Nora Seed é uma mulher cheia de talentos e poucas conquistas. Arrependida das escolhas que fez no passado, ela vive se perguntando o que poderia ter acontecido caso tivesse vivido de maneira diferente. Após ser demitida e seu gato ser atropelado, Nora vê pouco sentido em sua existência e decide colocar um ponto final em tudo. Porém, quando se vê na Biblioteca da Meia-Noite, Nora ganha uma oportunidade única de viver todas as vidas que poderia ter vivido. Neste lugar entre a vida e a morte, e graças à ajuda de uma velha amiga, Nora pode, finalmente, se mudar para a Austrália, reatar relacionamentos antigos – ou começar outros –, ser uma estrela do rock, uma glaciologista, uma nadadora olímpica... enfim, as opções são infinitas. Mas será que alguma dessas outras vidas é realmente melhor do que a que ela já tem?",
      autor: "Matt Heig",
      genero: "ficcao",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 308,
      editora: "Bertrand Brasil",
      vendas: 4274,
      lancamento: "2021-10-27",
      avaliacao: 4.3
    },
    {
      id: 13,
      titulo: "A Garota do Lago",
      preco: 11.83,
      imagem: livro13,
      sinopse: "Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.",
      autor: "Matt Heig",
      genero: "ficcao",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 296,
      editora: "Faro Editorial",
      vendas: 1074,
      lancamento: "2017-01-01",
      avaliacao: 4.8
    },
    {
      id: 14,
      titulo: "A Mecânica do Amor",
      preco: 37.44,
      imagem: livro14,
      sinopse: "Bel não sabe o que fazer quando se formar no colégio e nem quer pensar no assunto. Mas quando revela um talento especial para engenharia, é incentivada por uma professora a entrar para o clube de robótica da escola. O problema é que o clube é comandado por Teo, que além de gato e popular, ainda é mega inteligente e já tem cada passo do seu brilhante futuro bem planejado. Quando os dois se conhecem, o choque é instantâneo: eles se odeiam. Mas conforme trabalham juntos em robôs de combate, Teo logo reconhece o talento de Bel e percebe que não consegue parar de pensar na constelação de sardas no rosto da garota. E, pior ainda, se vê dedicado a aprender a discografia de Taylor Swift, de quem ela é fã. A mecânica do amor é o primeiro livro de romance contemporâneo da autora Alexene Farol Follmuth, conhecida pelo pseudônimo de Olivie Blake, e celebra a jornada de mulheres na área da ciência e da tecnologia em um enredo envolvente e apaixonante.",
      autor: "Alexene Farol Follmuth",
      genero: "romance",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 384,
      editora: "Alt",
      vendas: 174,
      lancamento: "2023-06-27",
      avaliacao: 4.8
    },
    {
      id: 15,
      titulo: "Eu Te Amei em Outra Vida",
      preco: 26.63,
      imagem: livro15,
      sinopse: "Uma sensível história de amor sobre dois jovens sensíveis e suas almas que insistem em se encontrar a cada nova vida. Evan Tatf tem tudo programado: Tirar um ano no Alaska, cuidar para que seu irmão mais novo e sua mãe estejam seguros e continuar o processo de terapia para entender o abandono de seu pai. Mas após o diagnstrico de sua mãe, tudo parece ruir, exceto algo expetacular: uma música que ninguém mais pode ouvir, a voz de alguém que Evan nunca conheceu... Shosh Bell tinha sonhos: Popular no colégio, ela está pronta para os seus estudos de arte em Los Angeles, e todos a apontam como uma estrela prestes a despontar. Mas quando um acidente tira a vida de sua irmã, sua vida muda bruscamente e seus sonhos não fazem mais sentido, Mas uma música surge, uma m que só ela pode ouvir... Acima de tudo, percorrendo tempo e espaco, uma música celestial une dois estranhos: seja para escapar de um assassino no século XIX, ou ser um cosmonauta norueguês em órbita, algo está acontecendo há muito tempo e continua a unir Evan e Shosh. Para leitores de A biblioteca da meia-noite, Eu te amei em outra vida explora a força do amor e como algumas almas são feitas umas para as outras.",
      autor: "David Arnold",
      genero: "romance",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 280,
      editora: "Livros da Alice",
      vendas: 460,
      lancamento: "2024-02-19",
      avaliacao: 4.1
    },
    {
      id: 16,
      titulo: "A Hipótese do Amor",
      preco: 45.03,
      imagem: livro16,
      sinopse: "Olive Smith, aluna do doutorado em Biologia da Universidade Stanford, acredita na ciência – não em algo incontrolável como o amor. Depois de sair algumas vezes com Jeremy, ela percebe que sua melhor amiga gosta dele e decide juntá-los. Para mostrar que está feliz com essa escolha, Olive precisa ser convincente: afinal, cientistas exigem provas. Sem muitas opções, ela resolve inventar um namoro de mentira e, num momento de pânico, beija o primeiro homem que vê pela frente. O problema é que esse homem é Adam Carlsen, um jovem professor de prestígio – conhecido por levar os alunos às lágrimas. Por isso, Olive fica chocada quando o tirano dos laboratórios concorda em levar adiante a farsa e fingir ser seu namorado. De repente, seu pequeno experimento parece perigosamente próximo da combustão e aquela pequena possibilidade científica, que era apenas uma hipótese sobre o amor, transforma-se em algo totalmente inesperado.",
      autor: "Ali Hazelwood",
      genero: "romance",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 336,
      editora: "Editora Arqueiro",
      vendas: 2369,
      lancamento: "2022-07-05",
      avaliacao: 4.2
    },
    {
      id: 17,
      titulo: "P.S. Eu Te Amo",
      preco: 18.70,
      imagem: livro17,
      sinopse: "“Um romance sensacional que prova que o amor verdadeiro nunca morre.” ―   Cosmopolitan Gerry e Holly tiveram a sorte que a maioria das pessoas não têm: encontraram suas almas gêmeas. Feitos um para o outro, sabiam que se amariam até o fim de suas vidas. O que não esperavam é que esse fim chegaria tão cedo: a descoberta tardia de um tumor cerebral em Gerry lhe dá poucos meses de vida. Devastada, Holly nem mesmo consegue imaginar como conseguirá viver sem o marido. Até que ela descobre que, antes de morrer, Gerry a deixou uma série de cartas, uma para cada mês e todas assinadas com “P.S. Eu te amo”. Com desafios e instruções para ajudá-la a seguir em frente, essas cartas vão fazer com que Holly ria, chore, viva e encontre a enorme coragem de criar novas memórias junto das pessoas que ama. Sucesso absoluto, P.S. Eu te amo é um dos romances contemporâneos mais aclamados do mundo, tendo uma legião de fãs. Em uma nova edição com tradução inédita da autora Iris Figueiredo, essa é uma história sobre luto, esperança e um tipo de amor que nunca morre. ",
      autor: "Cecelia Ahern",
      genero: "romance",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 416,
      editora: "HarperCollins",
      vendas: 1069,
      lancamento: "2023-04-15",
      avaliacao: 4.3
    },
    {
      id: 18,
      titulo: "O Exorcista",
      preco: 38.49,
      imagem: livro18,
      sinopse: "O livro que deu origem ao maior clássico cinematográfico de terror de todos os tempos, agora em edição de luxo com capa dura. Com mais de 13 milhões de exemplares vendidos, a obra de William Peter Blatty mudou a cultura pop para sempre, tornando-se um dos livros favoritos dos fãs de cinema. Quatro décadas após chocar o mundo inteiro, O Exorcista permanece uma metáfora moderna do combate entre o sagrado e o profano, em um dos romances mais macabros já escritos. Inspirado no caso real do exorcismo de um adolescente, o escritor William Peter Blatty publicou em 1971 a perturbadora história de Chris MacNeil, uma atriz que sofre com inesperadas mudanças no comportamento da filha de 11 anos, Regan. Quando todos os esforços da ciência para descobrir o que há de errado com a menina falham e uma personalidade demoníaca parece vir à tona, Chris busca a ajuda da Igreja para tentar livrar a filha do que parece ser um raro caso de possessão. Cabe a Damien Karras, um padre da Universidade de Georgetown, salvar a alma de Regan. Neste livro, Blatty conseguiu dar ao demônio a sua face mais revoltante: a corrupção de uma alma inocente. Um clássico incomparável do terror, O Exorcista não se trata apenas de uma simples história sobre o bem contra o mal, ou sobre Deus contra o Demônio, mas também sobre a renovação da fé.",
      autor: "William Peter Blatty",
      genero: "terror",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 336,
      editora: "HarperCollins",
      vendas: 4578,
      lancamento: "2019-08-12",
      avaliacao: 4.9
    },
    {
      id: 19,
      titulo: "Ninguém Vai te Ouvir Gritar",
      preco: 34.70,
      imagem: livro19,
      sinopse: "A Academia Masters é um dos internatos mais prestigiados dos Estados Unidos. Escondido em uma ilha na costa da Flórida e cercado por muros impenetráveis, o internato recebe novas turmas anualmente. Mas, além dos alunos, abriga segredos sinistros e ameaças letais. Entre os novatos de 2022, estão Andrew e Calvin, filhos do secretário de estado norte-americano. Logo na noite da festa de boas-vindas, Calvin desaparece, deixando apenas um pedaço de papel ensanguentado sobre a cama, onde alerta o irmão para que tome cuidado com algo ou alguém, cujo nome começa com a letra L. O desaparecimento de Calvin e a negligência de todos os adultos do internato empurra Andrew numa perigosa trama de mistérios que não estava descrita em sua carta de admissão.",
      autor: "Mark Miller",
      genero: "terror",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 264,
      editora: "Companhia Editora Nacional",
      vendas: 1845,
      lancamento: "2023-10-16",
      avaliacao: 4.7,
      },
      {
        id: 20,
        titulo: "Desenhos Ocultos",
        preco: 48.65,
        imagem: livro20,
        sinopse: "Profundamente assustador e original, Desenhos ocultos é uma experiência repleta de reviravoltas sobre redenção e os limites turvos entre vida e morte. Aos 21 anos, Mallory Quinn precisa trabalhar. Recém-saída da reabilitação, a jovem consegue um emprego na casa de Ted e Caroline Maxwell, que, aos olhos da vizinhança, levam uma vida perfeita. Sua principal função é tomar conta de Teddy, o filho de cinco anos dos dois. Mallory imediatamente se apaixona pelo trabalho: mora em um lugar só seu, sai para dar suas corridas noturnas e alcança a tão desejada estabilidade. Além disso, constrói laços sinceros com Teddy, um menino doce e tímido que nunca abandona seu caderno e seu lápis. Em seus desenhos, aparecem os elementos de sempre: árvores, coelhos, balões... Mas um dia, algo diferente surge no papel: um homem em uma floresta, arrastando o corpo inerte de uma mulher. A partir daí, as ilustrações de Teddy vão se tornando cada vez mais sinistras, e seus bonequinhos de palito logo se transformam em desenhos altamente realistas impossíveis de serem feitos por uma criança de cinco anos. Assustada, Mallory começa a se questionar se os desenhos não seriam vislumbres de um assassinato sem solução ocorrido décadas atrás nas redondezas, talvez relacionados a uma força sobrenatural. Agora, ela precisa correr contra o tempo para decifrar as imagens e salvar Teddy antes que seja tarde demais. “Sagaz, assustador e com uma trama magistral”, segundo Ransom Riggs ( O lar da srta. Peregrine para crianças peculiares ), Desenhos ocultos contém uma série de ilustrações que permeia o livro inteiro e é fundamental para compor sua narrativa. O resultado é um clima sombrio a cada página, com reviravoltas e desenhos de tirar o fôlego.",
        autor: "Jason Rekulak",
        genero: "terror",
        colecao: "",
        quantidade: 5,
        formato: "fisico",
        numeroDePaginas: 384,
        editora: "Intrínseca",
        vendas: 4682,
        lancamento: "2022-10-07",
        avaliacao: 4.0
    },
    {
      id: 21,
      titulo: "Dracula",
      preco: 15.22,
      imagem: livro21,
      sinopse: "Drácula é um clássico da literatura de terror e apresenta por meio de cartas, diários e notícias os ataques do vampiro Conde Drácula a moradores de Londres e da Transilvânia. O romance epistolar marcou o gênero e, mesmo não sendo a primeira obra a retratar esse mito literário, definiu o que conhecemos hoje como vampiro, influenciando a literatura, cinema e teatro.",
      autor: "Bram Stoker",
      genero: "terror",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 368,
      editora: "Principis",
      vendas: 4792,
      lancamento: "2020-04-27",
      avaliacao: 4.2,
      },
      {
      id: 22,
      titulo: "101 curiosidades - Futebol",
      preco: 8.92,
      imagem: livro22,
      sinopse: "O futebol é um esporte muito querido no Brasil e em diversos países. Você quer descobrir um montão de informações sobre esse esporte, como sua origem, os maiores jogadores da História e outros fatos curiosos? Então este livro é ideal para você. Vire as páginas e embarque neste incrível universo do futebol!",
      autor: "Paloma Blanca Alves Barbieri",
      genero: "esporte",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 32,
      editora: "Ciranda Cuktural",
      vendas: 462,
      lancamento: "2021-06-16",
      avaliacao: 3.8,
      },
      {
      id: 23,
      titulo: "Conforto na Escuridão: O Poder do Jiu-Jítsu Invisível",
      preco: 47.30,
      imagem: livro23,
      sinopse: "O maior lutador de jiu-jítsu do mundo e autor do best-seller Respire , Rickson Gracie traz um livro inspirador sobre os poderes invisíveis dentro de todos nós.  Um dos primeiros lemas da família Gracie dizia que “a autoconfiança e a paz de espírito adquiridas ao aprender jiu-jítsu vão ajudar a resolver o problema da insegurança humana”. Por isso, não é de se estranhar que Rickson Gracie tenha tomado para si a missão de difundir o jiu-jítsu como uma ferramenta de fortalecimento e transformação pessoal. Neste livro, Rickson detalha pela primeira vez as bases do jiu-jítsu invisível, o sistema de combate e filosofia de vida que desenvolveu ao longo de décadas como lutador profissional e professor da modalidade. “A mensagem de Conforto na escuridão vai muito além do jiu-jítsu. Rickson nos mostra o que é possível quando enfrentamos os desafios mais assustadores da vida, porque ele se recusa a abandonar sua busca pela forma mais elevada de si mesmo. “ ― Kelly Slater, campeão mundial de surfe “A abordagem de Rickson às artes marciais, ao jogo de combate desarmado, está muito além de sua idade. Ele é definitivamente uma inspiração para mim.” ― Conor McGregor, bicampeão do UFC “É necessária uma mentalidade fluida para se destacar tanto no combate quanto na vida. Rickson Gracie é a personificação dessa mentalidade.” ― José Padilha, diretor de Tropa de Elite e Narcos",
      autor: "Peter Maguire, Rickson Gracie",
      genero: "esporte",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 224,
      editora: "HarperCollins",
      vendas: 347,
      lancamento: "2024-11-18",
      avaliacao: 3.9,
      },
      {
      id: 24,
      titulo: "Corrida Manual Prático do Treinamento",
      preco: 17.92,
      imagem: livro24,
      sinopse: "A presente obra é um excelente exemplo da qualidade de produção de Alexandre Machado, que conseguiu, por meio deste trabalho, compartilhar conhecimentos, informações e orientação de caminhos para os profissionais que almejam trabalhar com corrida, como também para quem já desenvolve experiências nessa área e deseja continuar seu processo de transformação para melhor. o autor integra o conhecimento científico às questões mercadológicas, estabelecendo um cenário favorável àqueles que buscam um caminho para compor o seu formato de trabalho que apresente o foco em corrida. Trata-se de leitura obrigatória para todos os profissionais de Educação Física.",
      autor: "Alexandre Fernandes Machado",
      genero: "esporte",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 232,
      editora: "Phorte",
      vendas: 567,
      lancamento: "2013-05-22",
      avaliacao: 4.0,
      },
      {
      id: 25,
      titulo: "Ayrton: o Herói Revelado",
      preco: 75.20,
      imagem: livro25,
      sinopse: "Tive o privilégio de acompanhar de perto, desde 1972, a Fórmula 1 e a saga dos brasileiros na categoria mais importante do automobilismo mundial. Em 2004, depois de ler Ayrton: o herói revelado, ficou claro que a biografia escrita por Ernesto Rodrigues era o retrato mais completo, preciso e emocionante da trajetória de Ayrton Senna. Ninguém mergulhou com tanta sensibilidade, elegância e espírito jornalístico na história do gênio cuja vida eu acompanhei desde 1982, quando ele assombrou os autódromos ingleses nas disputas da Fórmula Ford, até aquele terrível 1º de maio de 1994, o dia em que todos ficamos órfãos de seu talento e carisma. Frequentemente, quando me perguntam sobre momentos específicos da minha vida ao lado do Ayrton, a única resposta que vem à mente é: “leia o livro do Ernesto Rodrigues”. E agora, enquanto escrevo as minhas memórias, Ayrton: o herói revelado é fonte de consulta valiosa, graças à profundidade da pesquisa e à forma de expor do meu amigo Ernesto. Vinte anos depois, ao ler a edição atualizada do livro, constato não apenas que eu estava certo quando apostei que ninguém faria uma biografia tão completa. Verifico, com prazer, passados trinta anos da perda de Senna, que, além da veracidade, permanência e relevância do que Ernesto escreveu em 2004, ele agora nos brinda uma atualização e uma contextualização do livro que abrange os acontecimentos significativos ocorridos depois de Ayrton, tanto na Fórmula 1 quanto no Brasil. Ayrton: o herói revelado, assim como Senna, continua importante, emocionante e inesquecível. ― Reginaldo Leme, Comentarista de Fórmula 1",
      autor: "Ernesto Rodrigues",
      genero: "esporte",
      colecao: "",
      quantidade: 5,
      formato: "fisico",
      numeroDePaginas: 512,
      editora: "Tordesilhas",
      vendas: 864,
      lancamento: "2024-04-30",
      avaliacao: 4.1,
      },
      {
      id: 26,
      titulo: "Pesquisa Acadêmica em Ciências Sociais: Diálogos Sobre Percursos Metodológicos",
      preco: 17.92,
      imagem: livro26,
      sinopse: "Intitulada “Pesquisa Acadêmica em Ciências Sociais: Diálogos sobre Percursos Metodológicos”, a obra divide-se em quatro capítulos. A partir de debates teóricos e empíricos sobre aspectos metodológicos centrais, a proposta do livro consiste em dialogar com algumas das possibilidades investigativas para a elaboração de uma pesquisa acadêmica em Ciências Sociais. Parte-se do pressuposto de que todo processo de construção e difusão do saber científico demanda, inevitavelmente, um olhar cuidadoso sobre as escolhas epistemológicas e de método a serem empreendidas no estudo. Ainda é preciso compreender que tais escolhas, ao invés de implicarem uma neutralização procedimental, dizem respeito a juízos valorativos sobre a realidade social em que a pesquisa e os pesquisadores se inserem. Realidade que, por sinal, transforma e é transformada pela investigação científica nas chamadas Ciências Sociais. O livro se estrutura em duas partes: (I) Diálogos teóricos: epistemologia e interdisciplinaridade; (II) Diálogos empíricos: aplicações qualitativas e quantitativas.",
      autor: "Bruna da Penha de Mendoça Coleho",
      genero: "academico",
      colecao: "",
      quantidade: 5,
      formato: "digital",
      numeroDePaginas: 88,
      editora: "Autografia",
      vendas: 98,
      lancamento: "2022-01-14",
      avaliacao: 4.1,
      },
      {
      id: 27,
      titulo: "Incursões na Escrita Acadêmico-Universitária: Letramento, Discurso e Enunciação",
      preco: 12.95,
      imagem: livro27,
      sinopse: "A obra está inserida nesta dupla linha de investigação: a competência tradutória e sua aquisição; e a didática da tradução. O livro é uma contribuição importante para a investigação sobre a competência tradutória, uma vez que aborda o estudo das diversas subcompetências essenciais para o tradutor (bilíngue, extralinguística, instrumental e estratégica) e também para o tradutólogo (competência teórica e metateórica). Além disso, são propostas diretrizes pedagógicas para o desenvolvimento dessas subcompetências, através das quais também se demarcam as pesquisas sobre a didática da tradução. Os aspectos tratados no livro são de natureza diversa – tradução de acrósticos, de piadas, da estrutura verbal em textos literários –, bem como contemplam o uso de recursos de documentação para tradutores.",
      autor: "Cármen Agustini, Ernesto Bertoldo",
      genero: "academico",
      colecao: "",
      quantidade: 5,
      formato: "digital",
      numeroDePaginas: 271,
      editora: "SciELO - EDUFU",
      vendas: 35,
      lancamento: "2017-01-01",
      avaliacao: 4.1,
      },
      {
      id: 29,
      titulo: "Letramento Acadêmico: Prática de Pesquisa e Produção Textual na Universidade",
      preco: 35.10,
      imagem: livro29,
      sinopse: "Quem chega na universidade entra em um mundo cheio de novidades e possibilidades, mas como de fato viver plenamente essa experiência universitária? Este livro oferece uma introdução à cultura acadêmica, especialmente nos cursos de graduação. Como se produz conhecimento científico na universidade? E por que meios divulgá-lo? A obra apresenta os gêneros textuais mais usados na academia e mostra como e quando colocá-los em prática, expondo suas particularidades e métodos de elaboração. Um manual básico, prático e essencial para ingressantes e também para aqueles que já são universitários e precisam de ferramentas para melhorar seu desempenho.",
      autor: "Luana Lopes Amaral",
      genero: "academico",
      colecao: "",
      quantidade: 5,
      formato: "digital",
      numeroDePaginas: 144,
      editora: "Contexto",
      vendas: 23,
      lancamento: "2025-03-31",
      avaliacao: 4.00,
      },
      {
      id: 30,
      titulo: "O Mal-estar na Escrita Acadêmica",
      preco: 44.73,
      imagem: livro30,
      sinopse: "Quem atua na universidade geralmente se protege na ilusão de que os estudantes universitários, pelo simples fato de terem chegado ao ensino superior, dominam totalmente as habilidades de leitura e, principalmente, de escrita. Ocorre que, assim como tantos outros bens e direitos desigualmente distribuídos na sociedade brasileira, também o letramento, isto é, o acesso à cultura letrada, ao mundo da palavra escrita, é privilégio e prerrogativa de muita pouca gente. O acesso à cultura letrada é, então, um problema político.Em ‘O mal-estar na escrita acadêmica’, Robson Cruz descreve e critica os construtos ideológicos que presidem os modos como a escrita é tratada no universo acadêmico. Esse livro é um convite a encarar as ideologias em que se concebe a escrita ora como um dom individual intransmissível, ora como uma capacidade quase autônoma de retratar fielmente a realidade. Há um mal-estar na academia no que diz respeito à escrita, um mal-estar falsamente individual. É chegada a hora da autocrítica que temos evitado fazer como defensores não só de ideais educacionais progressistas, mas de uma sociedade pautada por eles.",
      autor: "Robson Cruz",
      genero: "academico",
      colecao: "",
      quantidade: 5,
      formato: "digital",
      numeroDePaginas: 160,
      editora: "Parábola Editorial",
      vendas: 19,
      lancamento: "2024-10-05",
      avaliacao: 3.90,
      },
      {
      id: 28,
      titulo: "Como Produzir Textos Acadêmicos e Científicos",
      preco: 52.50,
      imagem: livro28,
      sinopse: "Escrever textos acadêmicos e científicos é essencial para quem ingressa na universidade. Mas em que consiste essa produção? Quais cuidados tomar? Como se preparar para os diferentes tipos de textos solicitados? Esta obra tem o objetivo de ser referência durante toda a trajetória acadêmica, desde a entrada na universidade como estudante, contemplando também o pesquisador e o docente. De forma bastante didática e detalhada, a professora Ada Magaly Matias Brasileiro discorre por 27 gêneros acadêmico-científicos, como artigo, projeto de pesquisa e relatório. É, enfim, uma obra pragmática que reúne as especificidades do ambiente acadêmico e, ao mesmo tempo, uma ferramenta de trabalho que não engessa a produção dos autores.",
      autor: "Ada Magaly Matias Brasileiro",
      genero: "academico",
      colecao: "",
      quantidade: 5,
      formato: "digital",
      numeroDePaginas: 272,
      editora: "Contexto",
      vendas: 57,
      lancamento: "2021-01-18",
      avaliacao: 4.00,
      }
    ];

    // Atualiza o estado com o mock
    setLivros(mockLivros);
  }, []);

  return (
    <LivrosContext.Provider value={{ livros, setLivros }}>
      {children}
    </LivrosContext.Provider>
  );
}